CenterFace:
    onnx_file:     "weights/centerface_bnmerged_transpose_224x224.onnx"
    engine_file:   "weights/centerface_bnmerged_transpose_224x224.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   224
    IMAGE_HEIGHT:  224
    image_order:   "BCHW"
    channel_order: "BGR"
    obj_threshold: 0.5
    nms_threshold: 0.45
    img_mean:      [ 0, 0, 0 ]
    img_std:       [ 1, 1, 1 ]    
    detect_mask:   False
    mask_thresh:   0.5
    landmark_std:  1
    feature_steps: [4]
    alpha:         1.0
    resize:        "keep_ratio"
