RetinaFace:
    onnx_file:     "weights/mnet_cov2.onnx"
    engine_file:   "weights/mnet_cov2.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   640
    IMAGE_HEIGHT:  640
    image_order:   "BCHW"
    channel_order: "BGR"
    obj_threshold: 0.5
    nms_threshold: 0.45
    img_mean:      [ 0, 0, 0 ]
    img_std:       [ 1, 1, 1 ]    
    detect_mask:   True
    mask_thresh:   0.5
    landmark_std:  0.2
    feature_steps: [32, 16, 8]
    anchor_sizes:  [[512, 256], [128, 64], [32, 16]]
    alpha:         1.0
    resize:        "keep_ratio"
